[build]
  command = "npm install"
  publish = "."

[functions]
  node_bundler = "esbuild"

  [functions."*"]
    external_node_modules = [
      "@google/generative-ai",
      "parse-multipart",
      "pdf-parse",
      "xlsx"
    ]
