[build]
  command = "npm install"
  publish = "."

[build.environment]
  NODE_VERSION = "20"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@google/genai", "xlsx"]

[functions."generateStatements"]
  timeout = 26
