[build]
  # The folder with your index.html
  publish = "."
  # Where your serverless functions are stored
  functions = "netlify/functions"

[dev]
  # For local testing with `netlify dev`
  functions = "netlify/functions"
  publish = "."

# Optional: Redirect all requests starting with /.netlify/functions to the functions folder
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
