[build]
  command = "npm install"
  publish = "."

[functions]
  node_bundler = "esbuild"

  [functions."*"]
    external_node_modules = [
      "multiparty",
      "pdf-parse",
      "node-fetch",
      "@google/generative-ai"
    ]
