[build]
  command = "npm install"
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["pdf-parse", "multiparty", "xlsx", "node-fetch"]
